__author__ = 'arkilic'
from mongoengine import *
from mongoengine.fields import *


class Header(Document):
    _id = IntField(primary_key=True, unique=True)
    start_time = DateTimeField(required=True)
    end_time = DateTimeField(required=False)
    update_time = DateTimeField()
    owner = StringField(max_length=20, required=True)
    beamline_id = StringField(max_length=20, required=True)
    custom = DictField(required=False)
    meta = {
        'indexes': ['-_id', '-start_time']
    }


class BeamlineConfig(DynamicDocument):
    _id = IntField(primary_key=True, required=False)
    headers = ListField(ReferenceField('Header', reverse_delete_rule=DO_NOTHING), required=True)
    energy = FloatField()
    wavelength = FloatField()
    i_zero = FloatField()
    custom = DictField(required=False)


class Event(DynamicDocument):
    """
    Event document constructor:
    _id: _id_hash generated by data collection routines using run_header
    seqno: Location of a specific data given data set
    event_type_id: Integer denoting a specific event's id
    run_id: user friendly indicator for a given run
    data: user specified python dictionary
    start_time: experiment start timestamp (python datetime.datetime object)
    end_time: experiment end timestamp (set to beginning of time in case of event failure
    description: text field describing the event
    """
    _id = IntField(primary_key=True, unique=True, required=True)
    headers = ListField(ReferenceField('Header', reverse_delete_rule=DO_NOTHING), required=True)
    event_type_id = IntField(min_value=0, required=True)
    run_id = IntField(min_value=0, required=True)
    seqno = IntField()
    start_time = DateTimeField(required=True)
    end_time = DateTimeField(required=False)
    description = StringField(max_length=50)
    data = DictField()
    meta = {
        'indexes': ['-headers', '-run_id', '-seqno']
    }


#TODO: Read and add fields to beamline_config and events from config file for a given session

