package:
  name: metadatastore
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../

build:
  string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy
    - pymongo

test:
  imports:
    - metadataStore
    - metadataStore.utilities
    - metadataStore.collectionapi
    - metadataStore.config
    - metadataStore.mdstools
    - metadataStore.database
    - metadataStore.sessionManager
    - metadataStore.userapi
    - metadataStore.api


about:
  license: 3-Clause BSD
